### ISSUE TITLE
Not supported?

### ISSUE THREAD

**Issue by Srokap** [AppGyver/steroids-runtime-tests#2]
Is `steroids test karma` supposed to still work? When I run it using `AppGyver Steroids2 4.0.13` I get just the command synopsis that seem to indicate that test is not recognized as valid command.

**Comment by harsaharsa** [comment]
Yup, that's been removed – we're running our tests in the app itself using a browser version of e.g. Mocha, see https://github.com/AppGyver/supersonic/tree/master/testSpecApp

I'll update the readme here accordingly.

**Comment by Srokap** [comment]
Awesome, thanks for clarification and link.
